### 멤버조회
GET localhost:8080/me


### 멤버조회
GET localhost:8080/me
Accept: application/xml


### 멤버조회
GET localhost:8080/members

### 멤버조회
GET localhost:8080/members/choi


### 멤버생성
POST localhost:8080/members
Content-Type: application/json
Accept-Language: en

{
  "id" : "member",
  "name" : "최정환",
  "age" : 27,
  "class" : "A",
  "role" : "MEMBER",
  "password": "member"
}